export const dashboardTempStub = {
    type: "ScatterPlot",
    isExplorable: false,
    id: 4039,
    version: 62,
    slug: "covid-confirmed-cases-since-100th-case",
    title: "Confirmed COVID-19 cases",
    subtitle:
        "The number of confirmed cases is lower than the number of total cases. The main reason for this is limited testing.",
    hideTitleAnnotation: true,
    xAxis: {
        scaleType: "linear"
    },
    yAxis: {
        min: 100,
        scaleType: "log",
        canChangeScaleType: true
    },
    externalDataUrl:
        "https://ourworldindata.org/grapher/data/variables/142582+142589+123.json?v=undefined",
    selectedData: [],
    minTime: 1,
    maxTime: "latest",
    timelineMinTime: 0,
    dimensions: [
        {
            property: "y",
            variableId: 142582,
            display: {
                name: ""
            }
        },
        {
            property: "x",
            variableId: 142589,
            display: {
                name: "Number of days since the 100th confirmed case",
                unit: "days",
                shortUnit: ""
            }
        },
        {
            property: "color",
            variableId: 123,
            display: {}
        }
    ],
    addCountryMode: "add-country",
    comparisonLines: [
        {
            label: "…every 2 days",
            yEquals: "100 * sqrt(2)^x"
        },
        {
            label: "…every 3 days",
            yEquals: "100 * 1.25992^x"
        },
        {
            label: "…every 10 days",
            yEquals: "100 * 1.07177^x"
        },
        {
            label: "…every 5 days",
            yEquals: "100 * 1.1487^x"
        },
        {
            label: "Cases double every day",
            yEquals: "100*2^x"
        }
    ],
    stackMode: "absolute",
    hideRelativeToggle: true,
    hasChartTab: true,
    hasMapTab: false,
    tab: "chart",
    variantName: "Trajectories",
    originUrl: "https://ourworldindata.org/coronavirus",
    isPublished: true,
    customColors: {},
    hideConnectedScatterLines: false,
    scatterPointLabelStrategy: "y",
    matchingEntitiesOnly: true,
    excludedEntities: [355, 51749],
    map: {
        targetYear: "latest",
        colorSchemeValues: [],
        colorSchemeLabels: [],
        customNumericColors: [],
        customCategoryColors: {},
        customCategoryLabels: {},
        customHiddenCategories: {},
        projection: "World"
    },
    data: {
        availableEntities: [
            "Afghanistan",
            "Africa",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Anguilla",
            "Antigua and Barbuda",
            "Argentina",
            "Armenia",
            "Aruba",
            "Asia excl. China",
            "Asia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bermuda",
            "Bhutan",
            "Bolivia",
            "Bonaire Sint Eustatius and Saba",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "British Virgin Islands",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Cape Verde",
            "Cayman Islands",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Congo",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Curacao",
            "Cyprus",
            "Czech Republic",
            "Democratic Republic of Congo",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Ethiopia",
            "Europe",
            "European Union",
            "Faeroe Islands",
            "Falkland Islands",
            "Fiji",
            "Finland",
            "France",
            "French Polynesia",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Gibraltar",
            "Greece",
            "Greenland",
            "Grenada",
            "Guam",
            "Guatemala",
            "Guernsey",
            "Guinea-Bissau",
            "Guinea",
            "Guyana",
            "Haiti",
            "High income",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "International",
            "Iran",
            "Iraq",
            "Ireland",
            "Isle of Man",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jersey",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Low income",
            "Lower middle income",
            "Luxembourg",
            "Macedonia",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Montserrat",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nepal",
            "Netherlands",
            "New Caledonia",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North America",
            "Northern Mariana Islands",
            "Norway",
            "Oceania",
            "Oman",
            "Pakistan",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Sint Maarten (Dutch part)",
            "Slovakia",
            "Slovenia",
            "Somalia",
            "South Africa",
            "South America",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Swaziland",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tanzania",
            "Thailand",
            "Timor",
            "Togo",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turks and Caicos Islands",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States Virgin Islands",
            "United States",
            "Upper middle income",
            "Uruguay",
            "Uzbekistan",
            "Vatican",
            "Venezuela",
            "Vietnam",
            "World excl. China and South Korea",
            "World excl. China, South Korea, Japan and Singapore",
            "World excl. China",
            "World",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        ]
    }
}
